language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer dumpautoload

script:
  - php -v
  - phpunit

notifications:
  email: true

addons:
  code_climate:
    repo_token: 1d39bf5b23666933719481b2b0f6371fb975bb7e55a313d07e953d474abfa8b8